version: '3.7'
services:
  postgres:
    image: postgres:16-alpine
    ports:
      - '5434:5434'
    volumes:
      - ./data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=app
      - POSTGRES_USER=app
      - POSTGRES_PASSWORD=9mREsvXDs9Gk89Ef
